//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW.DataHub.Portal.Console {
    
    
    public partial class ActivitiesMonitor {
        
        /// <summary>
        /// wucActivitiesMonitor1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MW.DataHub.Portal.Console.wuc.wucActivitiesMonitor wucActivitiesMonitor1;
    }
}
